language: node_js
node_js:
  - "0.10"

git:
  depth: 1

before_install:
  # - npm install -g --quiet --production --registry http://registry.npmjs.eu/ grunt-cli
  - npm install -g --quiet --production grunt-cli

install:
  - npm install --loglevel error --development

script:
  - npm test