language: node_js
node_js:
  - 0.10
  - 0.8

git:
  depth: 1

before_install:
  - npm install -g --quiet --production --registry http://registry.npmjs.eu/ grunt-cli

install:
  - npm install --loglevel error --development

script:
  - npm test